[WIP] Upgrade Dex to use llvm-hs@llvm-12.
Upgrading Dex to use LLVM 12 enables:
- Google-internal usage of Dex.
- Ability to hook into llvm-project top-of-tree functionality like MLIR.

Todos:
- Clean up OrcJIT API usages, along with API definitions from llvm-hs.
- Fix python/tests/jit_test.py, which is currently broken due to:

  ```
  OSError: dlopen(/Users/danielzheng/dex-lang/python/dex/libDex.dylib, 6): Symbol not found: _LLVM_Hs_CompileLayer_addModule
  ```
- Verify that tests pass and that bindings to work.
- Check benchmarks for performance changes.